routes/web.php
	Route::view('privacy_policy', 'privacy_pol');
	Route::view('refund_policy', 'refund_pol');
	Route::view('seo', 'seo');
  // Auth Routes
	Auth::routes();
});

Route::get('language-switch/{local}', 'LanguageSwitchController@languageSwitch')->name('languageSwitch');

// Routes With Web, Auth Middlewares
Route::group(['middleware' => ['web', 'auth']], function () {
    // User Account routes without subscription
	Route::get('account', 'UserAccountController@index');
	Route::get('account/profile', 'UserAccountController@edit_profile');
	Route::post('account/profile', 'UserAccountController@update_profile');
	Route::get('account/purchaseplan', 'UserAccountController@purchase_plan')->name('purchase');
	Route::get('account/purchase/{id}', 'UserAccountController@get_payment')->name('get_payment');
	Route::post('account/purchase', 'UserAccountController@subscribe');
	Route::get('account/billing_history', 'UserAccountController@history');
	Route::get('account/subtitle_appearance', 'UserAccountController@subtitle_appearance')->name("subtitle_appearance");
	Route::post('account/subtitle_save', 'UserAccountController@subtitle_save')->name("subtitle_save");
	Route::post('emailsubscribe', 'emailSubscribe@subscribe');
	Route::post('paypal_subscription', 'PaypalController@postPaymentWithpaypal')->name('paypal_subscription');
	Route::get('paypal_subscription', 'PaypalController@getPaymentStatus')->name('getPaymentStatus');
	Route::get('paypal_subscription_failed', 'PaypalController@getPaymentFailed')->name('getPaymentFailed');
    // Paypal Routes
	Route::get('paypal/cancel-subscription', 'UserAccountController@PaypalCancel')->name('cancelSubPaypal');
	Route::get('paypal/resume-subscription', 'UserAccountController@PaypalResume')->name('resumeSubPaypal');

    # Status Route
	Route::get('payment/status', 'PayuController@status');
	Route::post('payment/payu', 'PayuController@payment');

	// Bitcoin Routes
	Route::get('payment/bitcoin/status', 'BitcoinPaymentController@status');
	Route::post('payment/bitcoin', 'BitcoinPaymentController@payment');

});

// Routes With Web, Auth, Administrator Middlewares
Route::group(['middleware' => ['web', 'auth', 'is_admin', 'switch_languages']], function () {
	Route::get('admin', 'DashboardController@dashboard')->name('dashboard');
	Route::get('admin/profile', function(){
		$auth = Auth::user();
		return view('admin.profile', compact('auth'));
	});

	Route::resource('admin/menu', 'MenuController');
	Route::post('admin/menu/bulk_delete', 'MenuController@bulk_delete');
	Route::post('admin/menu/reposition', 'MenuController@reposition')->name('menu_reposition');
	
	Route::resource('admin/users', 'UsersController');
	Route::get('user/subscription/{id}', 'UsersController@change_subscription_show')->name('change_subscription_show');
	Route::post('user/subscription', 'UsersController@change_subscription')->name('change_subscription');
	Route::post('admin/users/bulk_delete', 'UsersController@bulk_delete');
	Route::resource('admin/movies', 'MovieController');
	Route::get('admin/movies/tmdb/translations', 'MovieController@tmdb_translations')->name('tmdb_movie_translate');
	Route::post('admin/movies/bulk_delete', 'MovieController@bulk_delete');
	Route::resource('admin/directors', 'DirectorController');
	Route::post('admin/directors/bulk_delete', 'DirectorController@bulk_delete');
	Route::resource('admin/actors', 'ActorController');
	Route::post('admin/actors/bulk_delete', 'ActorController@bulk_delete');

    // Genres Routes
	Route::resource('admin/genres', 'GenreController');
	Route::post('admin/genres/bulk_delete', 'GenreController@bulk_delete');
	Route::get('admin/update-to-english', 'GenreController@updateAll');

	Route::resource('admin/packages', 'PackageController');
	Route::post('admin/packages/bulk_delete', 'PackageController@bulk_delete');
	Route::resource('admin/faqs', 'FaqController');
	Route::post('admin/faqs/bulk_delete', 'FaqController@bulk_delete');
	Route::resource('admin/languages', 'LanguageController');
	Route::post('admin/languages/bulk_delete', 'LanguageController@bulk_delete');
	Route::resource('admin/settings', 'ConfigController');
	Route::get('admin/api-settings', 'ConfigController@setApiView');  
	Route::post('admin/api-settings', 'ConfigController@changeEnvKeys');  
	Route::resource('admin/coupons', 'CouponController');
	Route::post('admin/coupons/bulk_delete', 'CouponController@bulk_delete');
	Route::resource('admin/audio_language', 'AudioLanguageController');
	Route::post('admin/audio_language/bulk_delete', 'AudioLanguageController@bulk_delete');
	Route::resource('admin/home_slider', 'HomeSliderController');
	Route::post('admin/home_slider/bulk_delete', 'HomeSliderController@bulk_delete');
	Route::post('admin/home_slider/reposition', 'HomeSliderController@slide_reposition')->name('slide_reposition');
	Route::resource('admin/tvseries', 'TvSeriesController');
	Route::post('admin/tvseries/bulk_delete', 'TvSeriesController@bulk_delete');
	Route::get('admin/tvseries/tmdb/translations', 'TvSeriesController@tmdb_translations')->name('tmdb_tv_translate');
	Route::post('admin/tvseries/seasons', 'TvSeriesController@store_seasons');
	Route::patch('admin/tvseries/seasons/{id}', 'TvSeriesController@update_seasons');
	Route::delete('admin/tvseries/seasons/{id}', 'TvSeriesController@destroy_seasons');
	Route::get('admin/tvseries/seasons/{id}/episodes', 'TvSeriesController@show_episodes')->name('show_episodes');
	Route::post('admin/tvseries/seasons/episodes', 'TvSeriesController@store_episodes');
	Route::delete('admin/tvseries/seasons/episodes/{id}', 'TvSeriesController@destroy_episodes');
	Route::patch('admin/tvseries/seasons/episodes/{id}', 'TvSeriesController@update_episodes');
	Route::get('admin/report', 'ReportController@get_report');

    /////////////////////////
    // Customizable Routes //
    /////////////////////////
	Route::resource('admin/customize/landing-page', 'LandingPageController');
	Route::post('admin/customize/landing-page/bulk_delete', 'LandingPageController@bulk_delete');
	Route::post('admin/customize/landing-page/reposition', 'LandingPageController@reposition')->name('landing_page_reposition');
	Route::get('admin/customize/auth-page-customize', 'AuthCustomizeController@index');
	Route::post('admin/customize/auth-page-customize', 'AuthCustomizeController@store');

    // Site Policies Get Method
	Route::get('admin/term&con', function(){
		$config = \App\Config::whereId(1)->first();
		return view('admin.term&con', compact('config'));
	})->name('term_con');
	Route::get('admin/pri_pol', function(){
		$config = \App\Config::whereId(1)->first();
		return view('admin.pri_pol', compact('config'));
	})->name('pri_pol');
	Route::get('admin/refund_pol', function(){
		$config = \App\Config::whereId(1)->first();
		return view('admin.refund_pol', compact('config'));
	})->name('refund_pol');
	Route::get('admin/copyright', function(){
		$config = \App\Config::whereId(1)->first();
		return view('admin.copyright', compact('config'));
	})->name('copyright');

    // Site Policies Patch Method
	Route::patch('admin/term&con', function(\Illuminate\Http\Request $request){
		$config = \App\Config::whereId(1)->first();
		$input = $request->all();
		$config->update($input);
		return back()->with('updated', 'Terms & Condition has been updated');
	})->name('term&con');
	Route::patch('admin/pri_pol', function(\Illuminate\Http\Request $request){
		$config = \App\Config::whereId(1)->first();
		$input = $request->all();
		$config->update($input);
		return back()->with('updated', 'Privacy Policy has been updated');
	})->name('pri_pol');
	Route::patch('admin/refund_pol', function(\Illuminate\Http\Request $request){
		$config = \App\Config::whereId(1)->first();
		$input = $request->all();
		$config->update($input);
		return back()->with('updated', 'Refund Policy has been updated');
	})->name('refund_pol');
	Route::patch('admin/copyright', function(\Illuminate\Http\Request $request){
		$config = \App\Config::whereId(1)->first();
		$input = $request->all();
		$config->update($input);
		return back()->with('updated', 'Copyright text has been updated');
	})->name('copyright');

    /////////////////////////////////
    // Language Translation Routes //
    /////////////////////////////////
    // Header Translation Routes
	Route::get('admin/header-translations', 'HeaderTranslationController@index')->name('header-translation-index'); 
	Route::post('admin/header-translations', 'HeaderTranslationController@update');

    // Footer Translation Routes
	Route::get('admin/footer-translations', 'FooterTranslationController@index')->name('footer-translation-index'); 
	Route::post('admin/footer-translations', 'FooterTranslationController@update');
	
    // Home Page Translation Routes
	Route::get('admin/home-translations', 'HomeTranslationController@index')->name('home-translation-index'); 
	Route::post('admin/home-translations', 'HomeTranslationController@update'); 

    // Popover Detail Translation Routes
	Route::get('admin/popover-detail-translations', 'PopoverTranslationController@index')->name('popover-detail-translation-index'); 
	Route::post('admin/popover-detail-translations', 'PopoverTranslationController@update');


	Route::get('/api/token/generate', 'RESTAPIController@gettoken');
});

// Routes With Web, Auth And Subscriber Middlewares
Route::group(['middleware' => ['web', 'auth', 'is_subscriber', 'switch_languages']], function () {
    // User Main Movies And Shows routes Only With subscription
	Route::get('/{menu}', 'HomeController@index')->name('home');
    Route::any('/{menu}/others/{pagina?}/{year_selected?}/{genre_selected?}', 'HomeController@indexOthers')->name('home-others');
	Route::get('movie/detail/{id}', 'PrimeDetailController@showMovie')->name('showMovie');;
	Route::get('show/detail/{id}', 'PrimeDetailController@showSeasons')->name('showSeason');;
	Route::get('home/search', 'HomeController@search');
	Route::get('video/detail/director_search/{director}', 'HomeController@director_search');

app/Actor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Actor extends Model
{

    protected $fillable = [
      'name',
      'image',
      'tmdb_id'
    ];
}

app/Http/Controllers/ActorController.php
<?php

namespace App\Http\Controllers;

use App\Actor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ActorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $actors = Actor::all();
        return view('admin.actor.index', compact('actors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.actor.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
          'name' => 'required',
          'image' => 'nullable|image|mimes:jpeg,png,jpg'
        ]);

        $input = $request->all();

        if ($file = $request->file('image')) {
          $name = "actor_".time().$file->getClientOriginalName();
          $file->move('images/actors', $name);
          $input['image'] = $name;
        }

        Actor::create($input);
        return back()->with('added', 'Actor has been created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $actor = Actor::findOrFail($id);
        return view('admin.actor.edit', compact('actor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $actor = Actor::findOrFail($id);

        $request->validate([
          'name' => 'required',
          'image' => 'nullable|image|mimes:jpeg,png,jpg'
        ]);

        $input = $request->all();

        if ($file = $request->file('image')) {
          $name = "actor_".time().$file->getClientOriginalName();
          if ($actor->image != null) {
              $content = @file_get_contents(public_path().'/images/actors/'.$actor->image);
              if ($content) { 
                unlink(public_path()."/images/actors/".$actor->image);
              }
          }
          $file->move('images/actors', $name);
          $input['image'] = $name;
        }

        $actor->update($input);
        return redirect('admin/actors')->with('updated', 'Actor has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $actor = Actor::findOrFail($id);

        if ($actor->image != null) {
          $content = @file_get_contents(public_path().'/images/actors/'.$actor->image);
          if ($content) { 
            unlink(public_path()."/images/actors/".$actor->image);
          }
        }

        $actor->delete();
        return redirect('admin/actors')->with('deleted', 'Actor has been deleted');
    }

    public function bulk_delete(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'checked' => 'required',
        ]);

        if ($validator->fails()) {

            return back()->with('deleted', 'Please select one of them to delete');
        }

        foreach ($request->checked as $checked) {

            $actor = Actor::findOrFail($checked);
            
            if ($actor->image != null) {
              $content = @file_get_contents(public_path().'/images/actors/'.$actor->image);
              if ($content) { 
                unlink(public_path()."/images/actors/".$actor->image);
              }
            }

            Actor::destroy($checked);
        }

        return back()->with('deleted', 'Actors has been deleted');   
    }
}

resources/views/admin/actor/create.blade.php
@extends('layouts.admin')
@section('content')
  <div class="admin-form-main-block mrg-t-40">
    <h4 class="admin-form-text"><a href="{{url('admin/actors')}}" data-toggle="tooltip" data-original-title="Go back" class="btn-floating"><i class="material-icons">reply</i></a> Create Actor</h4>
    <div class="row">
      <div class="col-md-6">
        <div class="admin-form-block z-depth-1">
          {!! Form::open(['method' => 'POST', 'action' => 'ActorController@store', 'files' => true]) !!}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                {!! Form::label('name', 'Name') !!}
                <p class="inline info"> - Please enter actor name</p>
                {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
                <small class="text-danger">{{ $errors->first('name') }}</small>
            </div>
            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }} input-file-block">
              {!! Form::label('image', 'Director Image') !!} - <p class="inline info">Help block text</p>
              {!! Form::file('image', ['class' => 'input-file', 'id'=>'image']) !!}
              <label for="image" class="btn btn-danger js-labelFile" data-toggle="tooltip" data-original-title="Director pic">
                <i class="icon fa fa-check"></i>
                <span class="js-fileName">Choose a File</span>
              </label>
              <p class="info">Choose custom image</p>
              <small class="text-danger">{{ $errors->first('image') }}</small>
            </div>
            <div class="btn-group pull-right">
              <button type="reset" class="btn btn-info"><i class="material-icons left">toys</i> Reset</button>
              <button type="submit" class="btn btn-success"><i class="material-icons left">add_to_photos</i> Create</button>
            </div>
            <div class="clear-both"></div>
          {!! Form::close() !!}
        </div>  
      </div>
    </div>
  </div>
@endsection

resources/views/admin/actor/edit.blade.php
@extends('layouts.admin')

@section('content')
  <div class="admin-form-main-block mrg-t-40">
    <h4 class="admin-form-text"><a href="{{url('admin/actors')}}" data-toggle="tooltip" data-original-title="Go back" class="btn-floating"><i class="material-icons">reply</i></a> Edit Actor</h4>
    <div class="row">
      <div class="col-md-6">
        <div class="admin-form-block z-depth-1">
          {!! Form::model($actor, ['method' => 'PATCH', 'action' => ['ActorController@update', $actor->id], 'files' => true]) !!}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
                <small class="text-danger">{{ $errors->first('name') }}</small>
            </div>
            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }} input-file-block">
              {!! Form::label('image', 'Director Image') !!} - <p class="inline info">Help block text</p>
              {!! Form::file('image', ['class' => 'input-file', 'id'=>'image']) !!}
              <label for="image" class="btn btn-danger js-labelFile" data-toggle="tooltip" data-original-title="Director pic">
                <i class="icon fa fa-check"></i>
                <span class="js-fileName">Choose a File</span>
              </label>
              <p class="info">Choose custom image</p>
              <small class="text-danger">{{ $errors->first('image') }}</small>
            </div>
            <div class="btn-group pull-right">
              <button type="submit" class="btn btn-success"><i class="material-icons left">add_to_photos</i> Update</button>
            </div>
            <div class="clear-both"></div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/actor/index.blade.php
@extends('layouts.admin')
@section('content')
  <div class="content-main-block mrg-t-40">
    <div class="admin-create-btn-block">
      <a href="{{route('actors.create')}}" class="btn btn-danger btn-md"><i class="material-icons left">add</i> Create Actor</a>
      <!-- Delete Modal -->
      <a type="button" class="btn btn-danger btn-md" data-toggle="modal" data-target="#bulk_delete"><i class="material-icons left">delete</i> Delete Selected</a>   
      <!-- Modal -->
      <div id="bulk_delete" class="delete-modal modal fade" role="dialog">
        <div class="modal-dialog modal-sm">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <div class="delete-icon"></div>
            </div>
            <div class="modal-body text-center">
              <h4 class="modal-heading">Are You Sure ?</h4>
              <p>Do you really want to delete these records? This process cannot be undone.</p>
            </div>
            <div class="modal-footer">
              {!! Form::open(['method' => 'POST', 'action' => 'ActorController@bulk_delete', 'id' => 'bulk_delete_form']) !!}
                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                <button type="submit" class="btn btn-danger">Yes</button>
              {!! Form::close() !!}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="content-block box-body">
      <table id="full_detail_table" class="table table-hover">
        <thead>
          <tr class="table-heading-row">
            <th>
              <div class="inline">
                <input id="checkboxAll" type="checkbox" class="filled-in" name="checked[]" value="all" id="checkboxAll">
                <label for="checkboxAll" class="material-checkbox"></label>
              </div>
              #
            </th>
            <th>Image</th>
            <th>Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        @if ($actors)
          <tbody>
            @foreach ($actors as $key =>$actor)
              <tr>
                <td>
                  <div class="inline">
                    <input type="checkbox" form="bulk_delete_form" class="filled-in material-checkbox-input" name="checked[]" value="{{$actor->id}}" id="checkbox{{$actor->id}}">
                    <label for="checkbox{{$actor->id}}" class="material-checkbox"></label>
                  </div>
                  {{$key+1}}
                </td>
                <td><img
                  @if ($actor->image)
                    src="{{asset('/images/actors/' . $actor->image)}}"
                  @else
                    src="{{ asset('images/local.png') }}"
                  @endif
                    alt="Pic" width="70px" class="img-responsive img-thumbnail">
                </td>
                <td>{{$actor->name}}</td>
                <td>
                  <div class="admin-table-action-block">
                    <a href="{{route('actors.edit', $actor->id)}}" data-toggle="tooltip" data-original-title="Edit" class="btn-info btn-floating"><i class="material-icons">mode_edit</i></a>
                    <button type="button" class="btn-danger btn-floating" data-toggle="modal" data-target="#{{$actor->id}}deleteModal"><i class="material-icons">delete</i> </button>
                  </div>
                </td>
              </tr>
              <!-- Delete Modal -->
              <div id="{{$actor->id}}deleteModal" class="delete-modal modal fade" role="dialog">
                <div class="modal-dialog modal-sm">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <div class="delete-icon"></div>
                    </div>
                    <div class="modal-body text-center">
                      <h4 class="modal-heading">Are You Sure ?</h4>
                      <p>Do you really want to delete these records? This process cannot be undone.</p>
                    </div>
                    <div class="modal-footer">
                      {!! Form::open(['method' => 'DELETE', 'action' => ['ActorController@destroy', $actor->id]]) !!}
                          <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                          <button type="submit" class="btn btn-danger">Yes</button>
                      {!! Form::close() !!}
                    </div>
                  </div>
                </div>
              </div>
            @endforeach
          </tbody>
        @endif
      </table>
    </div>
  </div>
@endsection
@section('custom-script')
  <script>
    $(function(){
      $('#checkboxAll').on('change', function(){
        if($(this).prop("checked") == true){
          $('.material-checkbox-input').attr('checked', true);
        }
        else if($(this).prop("checked") == false){
          $('.material-checkbox-input').attr('checked', false);
        }
      });
    });
  </script>
@endsection